name: tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        versions:
          - version: nightly
            neovim: false
          - version: stable
            neovim: false
          - version: nightly
            neovim: true
          - version: stable
            neovim: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ubuntu System
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install sqlite3 libsqlite3-dev
      - name: Setup Windows System
        if: matrix.os == 'windows-latest'
        run: |
          choco install sqlite
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.versions.neovim }}
          version: ${{ matrix.versions.version }}
      - name: Run tests
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
          # XXX:
          # Overwrite %TMP% to point a correct temp directory.
          # Note that %TMP% only affects value of 'tempname()' in Windows.
          # https://github.community/t5/GitHub-Actions/TEMP-is-broken-on-Windows/m-p/30432#M427
          TMP: 'C:\Users\runneradmin\AppData\Local\Temp'
        run: ./run.sh
